**numpy 패키지를 np라는 별칭으로 임포트**

In [3]:
import numpy as np

**넘파이 버전과 환경구성 출력하기**

In [4]:
print(np.__version__)
np.show_config()

1.17.4
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mylov/Anaconda3/envs/tf20\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/mylov/Anaconda3/envs/tf20\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/mylov/Anaconda3/envs/tf20\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libra

**10인 크기의 널 백터 생성하기**

In [5]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**특정 배열의 메모리 크기 확인하기**

In [6]:
z = np.zeros((10, 10))
print('{} bytes'.format(z.size * z.itemsize))

800 bytes


**넘파이 함수 설명 확인하기**

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added. If ``x1.shape != x2.shape``, they must be broadcastable to a common shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None`

**다섯번째 원소의 값은 1이고 나머진 원소의 값은 0인 널백터 생성**

In [12]:
z = np.zeros(10)
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


**백터의 원소값이 10에서 49인 벡터 생성하기**

In [13]:
z = np.arange(10, 50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [14]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``

In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
%run 'python -c "import numpy; numpy.info(numpy.add)"'

ERROR:root:File `"'python.py"` not found.


In [1]:
import test

Hello Python


In [3]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L] 
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np

In [11]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [12]:
np.array([3.14, 1, 2, 3, 4])

array([3.14, 1.  , 2.  , 3.  , 4.  ])

In [13]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([[1], [2], [3]])
print(M)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]


In [20]:
print(M.shape)
print(v.shape)

(3, 3)
(3, 1)
