In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
type(L[0])

int

In [6]:
L2 = [str(c) for c in L] 
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [7]:
type(L2[0])

str

In [8]:
L3 = [True, '2', 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [9]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import numpy as np

In [11]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [12]:
np.array([3.14, 1, 2, 3, 4])

array([3.14, 1.  , 2.  , 3.  , 4.  ])

In [13]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [14]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [15]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [19]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
v = np.array([[1], [2], [3]])
print(M)
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1]
 [2]
 [3]]


In [20]:
print(M.shape)
print(v.shape)

(3, 3)
(3, 1)
